= Capítulo X

- Mostrar a duplicação de dados entre cliente e funcionário.
- Analisar os atributos e métodos comuns a cada classe.
- Pensar nos tipos de pessoas que existem na sociedade (em termos jurídicos)
- Criar projeto no netbeans para introduzir herança de Pessoa, Pessoa Física, Pessoa Juridica, Cliente, Funcionário e Fornecedor.
- Visibilidade com modificadores private e public e introduzir o termo encapsulamento: refatorar o método cpf válido, extraindo novos métodos privados.
- Classes Mãe (Super classe) e classes Filhas (subclasses)
- O que as filhas herdam da mãe.
- Herança múltipla: classe pai e mãe?

== Projeto

Criar projeto utilizando herança, contendo classes de pessoas para um sistema acadêmico.
Tal sistema deve possuir classes como aluno, professor e funcionário.
Defina e implemente as classes mães e filhas para tal projeto,
incluíndo os atributos e métodos que achar necessários.

- Repetir o mesmo processo feito de refatorar a função de validar CPF com a função para validar CNPJ  
  (extraindo novos métodos dela). Definir a visibilidade dos métodos extraídos.
  Relembrar que tais métodos são para uso interno da classe: fora dela nem precisamos saber que eles existem.
- Mostrar os níveis de visibilidade protected e package (default) e como funcionam com herança
- Os métodos extraídos do cpfValido podem ser definidos como protected.
  O remove símbolos, por exemplo, pode ir pra classe pessoa para 
  ser usado por PessoaFisica e PessoaJuridica.