= Capítulo 9
- Introdução à encapsulamento (visibilidade)
    * Criar classe Venda de forma simplificada, contendo um atributo Produto + quantidade, um cliente e um vendedor
    * mostrar que os atributos são acessíveis dentro de qualquer lugar da classe: criar um método valorTotal na venda para mostrar isso
    * Criar um método salvar() na venda que vai reduzir o estoque do produto,
      acessando os atributos diretamente
    * apresentar os modificadores de acesso público e privado e como o código acessando 
      atributos diretamente de fora da classe produto param de funcionar.
- Alterar a venda para permitir incluir vários itens
- No setter do produto na classe Venda, verificar se o produto informado
    tem estoque maior que zero para poder atribuir o produto à venda.
    Caso o estoque seja zero ou negativo, exibir a mensagem "O produto informado não possui estoque e não pode ser vendido".
 
== Adicionar Funcionalidades Básicas

- Cliente: validar email, validar CPF, validar attributos nos setters
  - CPF: Usar uma função pronta, depois refatorar tal função (criar a função do zero seria mais fácil,
    mas o objetivo é mostrar como a POO pode tornar mais claro um código que antes era confuso e repetivo.)
- Filial: validar CNPJ.

= Capítulo X

- Mostrar a duplicação de dados entre cliente e funcionário.
- Analisar os atributos e métodos comuns a cada classe.
- Pensar nos tipos de pessoas que existem na sociedade (em termos jurídicos)
- Criar projeto no netbeans para introduzir herança de Pessoa, Pessoa Física, Pessoa Juridica, Cliente, Funcionário e Fornecedor.
- Visibilidade com modificadores private e public e introduzir o termo encapsulamento: refatorar o método cpf válido, extraindo novos métodos privados.
- Classes Mãe (Super classe) e classes Filhas (subclasses)
- O que as filhas herdam da mãe.
- Herança múltipla: classe pai e mãe?

== Projeto

Criar projeto utilizando herança, contendo classes de pessoas para um sistema acadêmico.
Tal sistema deve possuir classes como aluno, professor e funcionário.
Defina e implemente as classes mães e filhas para tal projeto,
incluíndo os atributos e métodos que achar necessários.

- Repetir o mesmo processo de refatorar a função de validar CPF com a função de validar CNPJ  
  (extraindo novos métodos dela). Definir a visibilidade dos métodos extraídos.
  Relembrar que tais métodos são para uso interno da classe: fora dela nem precisamos saber que eles existem.
- Mostrar os níveis de visibilidade protected e package (default) e como funcionam com herança
- Os métodos extraídos do cpfValido podem ser definidos como protected.
  O remove símbolos, por exemplo, pode ir pra classe pessoa para 
  ser usado por PessoaFisica e PessoaJuridica.