:imagesdir: images

== Ambiente de Desenvolvimento Java

Antes de prosseguir para a parte prática, temos que instalar as ferramentas necessárias para aplicarmos os conceitos de POO em Java.
Para podermos compilar aplicações Java, precisamos do Java Development Kit (JDK): o Kit de Desenvolvimento Java.
A forma mais fácil de instalar estas ferramentas depende do sistema operacional utilizado, como apresentado a seguir.

=== JDK no Windows

No Windows o JDK deve ser baixado manualmente no site da http://oracle.com/technetwork/java/javase/downloads/[Oracle].

O vídeo abaixo mostra o processo de instalação passo-a-passo, incluindo as configurações necessárias para 
compilar e executar programas Java pelo prompt de comandos no Windows. 

video::CdzJcXYQxt8[youtube, width="100%", height="300vh"]

=== JDK no Linux

A instalação do JDK no Linux é bem mais simples. Basta executar o comando abaixo no terminal, de acordo com a distribuição Linux que estiver utilizando.
Aqui está sendo usada a versão 24 do OpenJDK, mas pode ser que sua distribuição Linux não tenha tal versão disponível.
Assim, tente versões mais antigas como 21 ou 17.

- Debian e derivados (como Ubuntu e Linux Mint): `sudo apt-get install openjdk-24-jdk`
- Red Hat e derivados (como Fedora e CentOS): `sudo yum install openjdk-24-jdk`
- ArchLinux e derivados (como ArchBang): `sudo pacman install openjdk-24-jdk`
