:imagesdir: images

== Quantidade de Objetos em um Relacionamento

Quando criamos os relacionamentos `Empresa` -> `Funcionario` (para definir quem era o gerente da empresa) e entre `Empresa` -> `Cidade` (para indicar em qual cidade a empresa está situada), apenas incluímos os atributos `Funcionario gerente` e `Cidade cidade` dentro da `Empresa`. 

Fizemos isso de forma intuitiva, pois sabemos, por exemplo, que uma empresa (matriz ou filial) está situada em apenas uma cidade, definindo então quantos objetos de cada lado da associação podem ser envolvidos. Tal informação é chamada de cardinalidade ou multiplicidade. Assim, de forma simplificada, o relacionamento `Empresa` -> `Cidade` tem uma cardinalidade 1..1 (lê-se "1 pra 1"), indicando que podemos relacionar 1 objeto `Empresa` com no máximo 1 objeto `Cidade`.

Para criarmos um relacionamento 1..1 entre duas classes, precisamos apenas incluir um atributo do tipo da classe de destino (onde a seta chega), dentro da classe de origem (de onde a seta parte). O código abaixo apresenta os relacionamentos de `Empresa` para `Cidade` e `Funcionario`.

[source,java]
----
public class Empresa
{
    private String nomeFantasia;
    private String razaoSocial;
    private String cnpj;
    private String endereco;
    private String telefone;
    private String site;
    private boolean matriz;

    //Cria um relacionamento 1..1  entre Empresa -> Cidade
    private Cidade cidade;    

    //Cria um relacionamento 1..1  entre Empresa -> Funcionario
    private Funcionario gerente;

    //Métodos omitidos por simplificação
}
----

Isto define que os objetos de tais classes podem se relacionar. Para relacionar os objetos de fato, uma `Empresa` e uma `Cidade` neste exemplo, normalmente precisamos ter um _setter_ para o atributo que define o relacionamento, como o atributo `cidade` dentro da classe `Empresa`. Assim, ao chamarmos o método `setCidade()` a partir de um objeto `Empresa`, somente neste momento é que estaremos relacionando um objeto `Cidade` a um `Empresa`.
