:imagesdir: images

==== Quantidade de Objetos em um Relacionamento

Quando criamos os relacionamentos `Empresa` -> `Funcionario` para definir quem era o gerente da empresa e entre `Empresa` -> `Cidade` para indicar em qual cidade a empresa está situada, apenas incluímos os atributos `Funcionario gerente` e `Cidade cidade` dentro da empresa. Assim, a empresa tem um gerente e é situada em uma cidade.

Fizemos isso de forma intuitiva, pois sabemos, por exemplo, que uma empresa (matriz ou filial) está situada em apenas uma cidade, definindo então quantos objetos de cada lado da associação podem ser envolvidos. Tal informação é chamada de cardinalidade ou multiplicidade. Assim, de forma simplificada, o relacionamento `Empresa` -> `Cidade` tem uma cardinalidade 1 pra 1, indicando que podemos relacionar 1 objeto Empresa com no máximo 1 objeto Cidade.

Quando temos um relacionamento 1 pra 1, para criarmos tal relacionamento entre as duas classes envolvidas, precisamos apenas incluir um atributo do tipo da classe de destino (onde a seta chega), dentro da classe de origem (de onde a seta parte). No caso do exemplo `Empresa` -> `Cidade`, temos que apenas colocar um atributo da classe `Cidade` dentro da classe `Empresa`.

Isto define que os objetos de tais classes podem se relacionar. Para relacionar os objetos de fato, neste exemplo 1 `Empresa` e 1 `Cidade`, normalmente precisamos ter um setter para o atributo que define o relacionamento (como o atributo `cidade` dentro da classe `Empresa`). Assim, ao chamarmos o método `setCidade()` a partir de um objeto `Empresa`, estaremos efetivamente relacionando um objeto `Cidade` a um `Empresa`.

Apesar de ser natural pensarmos na cardinalidade entre `Empresa` e `Cidade` como 1 para 1, na verdade tal cardinalidade é n para 1, ou seja, vários objetos `Empresa` podem estar relacionados a mesma cidade. Você pode pensar que seria o mesmo que dizer que 1 `Empresa` então está relacionada a 1 `Cidade`. Se pensarmos assim, podemos representar tal cardinalidade como 1 -> 1, seguindo a direção da seta neste relacionamento entre as duas classes. E então, ao avaliar o relacionamento no sentido contrário (`Empresa` <- `Cidade`), então apenas inverteríamos a seta na cardinalidade, ficando 1 <- 1, que lendo na direção da seta indica que 1 `Cidade` possui no máximo 1 `Empresa`.

Mas sabemos que isto não é verdade, uma cidade pode ter várias (n) empresas. Por esse motivo, é mais simples interpretarmos relacionamentos semelhantes à `Empresa` -> `Cidade` como n -> 1, pois se criarmos o relacionamento no sentido contrário, apenas inverteremos a seta e teremos n <- 1, indicando que 1 cidade pode ter várias empresas.
