= Polimorfismo
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0
:revealjs_slideNumber: true
:source-highlighter: highlightjs
:icons: font
:imagesdir: images
:allow-uri-read:
:safe: unsafe
:numbered:
:listing-caption: Listing

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== Polimorfismo Estático

Tipos de Polimorfismo Estático 

- Ad Hoc (Method Overload)
- Paramêtrico (Generics)

== Polimorfismo Ad Hoc (Method Overload)

- É a chamada sobrecarga de método (method overload): criação de várias versões de uma mesmo método
- Ad hoc significa "específico e temporário". 
- Um método vai se comportar de forma específica, de acordo com os valores que foram passados a ele. 

== Polimorfismo Ad Hoc (Method Overload)

- O método não terá sempre um mesmo comportamento. 
- O comportamento em um determinado momento depende dos valores passados ao método. 
- O comportamento do método é temporariamente definido de acordo com tais valores. 
- Se em uma próxima chamada forem passados diferentes valores, o comportamento pode ser diferente para este outro momento. 

== Polimorfismo Ad Hoc (Method Overload)

- As chamadas dos métodos dependem de um tipo específico definido. 
- De acordo com os tipos, uma determinada versão de um mesmo método é chamada. 
- Permite executar diferentes versões da mesma função, de acordo com os tipos e quantidade de parâmetros.

== Polimorfismo Ad Hoc (Method Overload)
- Exemplos: os vários construtores de uma classe 
- Eles são métodos com o mesmo nome, mas parâmetros diferentes.

== Polimorfismo Ad Hoc (Method Overload): exercícios

Novos métodos sobrecarregados a inserir:

- Produto.removeEstoque(ItemVenda item)
- Produto.addEstoque(ItemVenda item)
- Estado.addCidade(List<Cidade> cidades)
- Estado.addCidade(Cidade... cidades) 

== Polimorfismo Paramêtrico (Generics)
- As chamadas dos métodos NÃO dependem de um tipo específico definido. 
- Se chamarmos um método genérico m(T param), o método a ser chamado não depende do tipo T.
- Sempre será chamado o método m que recebe um parâmetro T. 

== Polimorfismo Paramêtrico (Generics)

- Exemplos de Classes Genéricas: List e ArrayList

== Polimorfismo Paramêtrico (Generics)

Criando Classes e Métodos Genéricos

- class RepositorioPessoas<T extends Pessoa>
    * métodos para buscar pessoa mais velha
    * buscar pessoas sem CPF
    * buscar pessoas agrupando por cidade

// - Métodos Genéricos (sem uma classe genérica)

== Polimorfismo Paramêtrico (Generics)

- Podemos unir method overload e generics criando um método genérico m(T param) e depois um método sobrecarregado m(T param, int x). 
- O método é chamado genérico por usar um tipo T. 

== Polimorfismo Paramêtrico (Generics)

- No caso do exemplo, há duas versões desse mesmo método genérico, logo é é genérico e sobrecarregado. 
- Se chamarmos o método passando um tipo T e um int, estaremos chamando o segundo método e não o primeiro. 
- Um método genético executa uma mesma versão de uma função para diferentes tipos e quantidade de parâmetros.

// === Sobrecarga de operadores 
// Java não suporta, linguagens como Lua e C++ suportam

== Dinâmico - Subtipagem
- Lista de dependentes PessoaFisica do Funcionario
- Um método como addDependente(PessoaFisica dependente) aceita objetos PessoaFisica e de qualquer subclasse.
- Isto quer dizer que uma variável de uma classe B pode armazenar objetos B e de subclasses de B (como C ou D),
mas não pode armazenar objetos de uma superclasse de B como A.

== Dinâmico - Subtipagem

- No exemplo, dependente pode armazenar objetos da classe PessoaFisica e das subclasses Cliente e Funcionario,
mas não pode armazenar objetos da superclasse Pessoa. 
- Isto porque Cliente e Funcionario são PessoaFisica
mas nem toda Pessoa é uma PessoaFisica. Uma Empresa não é uma PessoaFisica mas sim uma PessoaJuridica.

== Dinâmico - Method Override: Exercícios

Renomear o atributo salario para salarioBase e calcular o salario total de acordo com o tipo
de funcionario. Assim, teríamos uma classe base Funcionario e outras como Vendedor e Gerente.
No gerente o salário total é o base + um percentual de participação nos lucros. Os lucros vão 
ser obtidos a partir da classe Empresa.

No funcionario o salário total é o base + um percentual sobre as vendas realizadas.
As vendas do funcionario vão ser obtidas a partir de um atributo List<Venda> vendas.

== Dinâmico - Method Override

- Uma subclasse pode sobrescrever um método alterando completamente seu comportamento
ou extendendo sua funcionalidade.
- Porque usar @Override
- No caso de construtores, não há como modificar completamente eles em subclasses.

== Diferenças entre subtipagem e polimorfismo estático

O que muda ao declarar um método m(SuperClass param) e m(T param): Usando T ou SuperClass, podemos passar como parâmetro qualquer objeto da classe indicada por T ou SuperClass ou qualquer objeto de uma subclasse desses tipos. Usando T, ao acessar param, teremos acesso à todos os métodos que temos permissão para acessar, que tenham sido declarados diretamente no tipo T ou em alguma de suas superclasses.

== Diferenças entre subtipagem e polimorfismo estático

Usando SuperClass, mesmo que seja passado um objeto de uma subclasse, não teremos como acessar diretamente qualquer método disponível na subclasse a qual o parâmetro representa. Adicionalmente, se o tipo T foi definido no nível da classe não no método, isto garante que para uma determinada instância do objeto onde o método m foi declarado, toda vez que chamarmos o método m naquela instância, precisaremos passar um objeto T do mesmo tipo. 


== Diferenças entre subtipagem e polimorfismo estático

No caso do uso da SuperClass, para uma instância ownerOfM, podemos uma hora passar um objeto de uma subclasse A e depois passar um objeto de uma subclasse B, por exemplo: ownerOfM.m(a1) e depois ownerOfM.m(b1). 

== Diferenças entre subtipagem e polimorfismo estático

No caso de uso de T, para uma instância ownerOfM, podemos apenas passar objetos do tipo T específico definido ao criar onwerOfM. Assim, se para ownerOfM o tipo T foi definido como da classe A, só podemos chamar m com instância de A, como: ownerOfM.m(a1) e ownerOfM.m(a2). Se SuperClass fosse usado para uma lista, permitiria que a lista tivesse elementos de qualquer subclasse de SuperClass, o que pode não ser o desejado. 

== Diferenças entre subtipagem e polimorfismo estático

Uma lista onde SuperClass é Veiculo poderia contar objetos Avio, Carro, Barco, etc.
Mesmo que a lista fosse de Carro e quissessemos só um tipo de carro (carros normais, da classe Carro e não subclasses
de carro como CarroVoador), usando SuperClass não temo como restringir isso.
Se usarmos T e dissermos que tal tipo representa Carro, só podemos adicionar elementos Carro à lista
e não subclasses como CarroVoador ou CarroAnfibio.